### ISSUE TITLE
How to use parallelism with PHPUnit?

### ISSUE THREAD

**Issue by martinbean** [CircleCI-Public/sample-php-laravel#13]
I’m struggling to find any documentation or references on how to run PHPUnit across multiple containers with parallelism.

If I have `parallelism: 2` in my **.circleci/config.yml** file, the whole PHPUnit test suite is ran on both instances. How can I “split” my test suite so that some tests are ran in one container, and the other tests ran in the second container?

**Comment by andreportaro** [comment]
Not completely sure this works, but I'm attempting to use this now: https://qiita.com/takeru0757/items/2bf3f06e210e450488be

**Comment by ryanwohara** [comment]
This repository doesn't use parallelism for this exact reason, and Python is similar. There's no native support to run only a subset of your tests.
I advise reaching out to our community if you're still stuck:
https://discuss.circleci.com/

**Comment by martinbean** [comment]
@ryanwohara I did. They were no use despite opening several support tickets. Agents just kept pointing me to the incomplete and vague docs.

It _is_ possible because plenty of other platforms support running a PHPUnit test suite in parallel.

**Comment by andrewmclagan** [comment]
Their docs are so so incredibly vague on this subject. They should boot example repositories for all popular langs.

**Comment by martinbean** [comment]
@andrewmclagan Complete non-issue now as I ditched CircleCI.

**Comment by andrewmclagan** [comment]
Also ditching in favour of Github actions... If Circle staff see this: Lack of support and communication is the primary reason.

good bye ;-)
