### ISSUE TITLE
Official Docker image

### ISSUE THREAD

**Issue by vojtasvoboda** [CircleCI-Public/sample-php-laravel#2]
Hello guys, is there some official Docker image, same as `notnoopci/php:7.1.5-browsers` but from [https://hub.docker.com/r/circleci/php/tags/](https://hub.docker.com/r/circleci/php/tags/)?

I have tried `7.1.5-apache-browsers` but it does not have `composer` pre-installed.

**Comment by lesterchan** [comment]
I am using `circleci/php:7.1-node-browsers` and installed my own composer `'curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer'`

**Comment by vojtasvoboda** [comment]
Thank you, it works!
