### ISSUE TITLE
Asset building

### ISSUE THREAD

**Issue by benswinburne** [CircleCI-Public/sample-php-laravel#3]
Can you perhaps demonstrate how to build assets with yarn too as this is a common requirement in Laravel projects.

Simply running `yarn install` doesn't work as yarn isn't installed.

I assume we could run a parallel job in a node container but then presumably the result of both containers would need to be merged to run tests against.

For example

    composer install
    yarn production
    phpunit
    yarn test
    php artisan dusk

The last one needs compiled assets and a working php application.

**Comment by ryanwohara** [comment]
https://circleci.com/gh/CircleCI-Public/circleci-demo-php-laravel/18
